- Makefile
- README.md
- azure-pipelines.yml
- ci/diagnostics.sh
- ci/install-riff.sh
- ci/publish.sh
- ci/run-tests.sh
- ci/stage.sh
Create a releases chart repository that includes FATS validated charts. Test PRs with unauthenticated FATS runs.
> Add FATS tests and publish on passage

- README.md
- azure-pipelines.yml
- ci/cleanup-riff.sh
- overlays/helm-labels.yml
Apply helm standard labels to all resources
https://helm.sh/docs/chart_best_practices/#standard-labels
> Add uninstall instructions

- Makefile
Refs https://istio.io/blog/2019/istio-security-003-004/
> Update Istio to 1.1.13

- README.md
> Add command to remove knative.deployers for uninstall

- charts/riff-builders/templates.yaml
- charts/riff/templates.yaml.tpl
Pin Knative build templates on lifecycle 0.3
> Consume lifecycle 0.4 buildpacks

- README.md
- charts/knative/Chart.yaml
- charts/kpack/Chart.yaml
- charts/riff-build/Chart.yaml
- charts/riff-builders/Chart.yaml
- charts/riff-core-runtime/Chart.yaml
- charts/riff-knative-runtime/Chart.yaml
- charts/riff-streaming-runtime/Chart.yaml
- charts/riff/Chart.yaml
> rollback required helm to 2.13

- charts/riff-build/templates.yaml
- charts/riff-core-runtime/templates.yaml
- charts/riff-knative-runtime/templates.yaml
- charts/riff-streaming-runtime/templates.yaml
- better logs
- better local build support
> Consume latest system

- .github/workflows/ci.yaml
- charts/istio/values.yaml
- charts/package.sh
> Resolve known image tags to digest

- charts/riff-build/templates.yaml
- charts/riff-core-runtime/templates.yaml
- charts/riff-knative-runtime/templates.yaml
- charts/riff-streaming-runtime/templates.yaml
- overlays/crd-install.yml
> Fix crd-install overlay

- charts/cert-manager/overlays-uncharted/api-service.yaml
- charts/keda/overlays-uncharted/api-service.yaml
- charts/knative/overlays-uncharted/api-service.yaml
- charts/unpackage.sh
Derived from https://github.com/k14s/kapp/issues/12#issuecomment-528585156
> Add hints for kapp where needed

- .github/workflows/cleanup-riff-kapp.sh
- .github/workflows/install-riff-kapp.sh
- README.md
Adding kapp install instructions. Preserving helm install instructions.
> Add install/uninstall instructions for uncharts

- .github/workflows/run-tests.sh
Signed-off-by: Emily Casey <ecasey@pivotal.io>
> FATs explicitly sets --ingress-policy External

- charts/riff-build/templates.yaml
- charts/riff-builders/templates.yaml
- charts/riff-core-runtime/templates.yaml
- charts/riff-knative-runtime/templates.yaml
- charts/riff-streaming-runtime/templates.yaml
Signed-off-by: Emily Casey <ecasey@pivotal.io>
> bump system and build template

- charts/riff-build/templates.yaml
- charts/riff-core-runtime/templates.yaml
- charts/riff-knative-runtime/templates.yaml
- charts/riff-streaming-runtime/templates.yaml
Fixes https://github.com/projectriff/charts/issues/110
> Bump riff system

- charts/riff-build/templates.yaml
- charts/riff-builders/templates.yaml
- charts/riff-core-runtime/templates.yaml
- charts/riff-knative-runtime/templates.yaml
- charts/riff-streaming-runtime/templates.yaml
Includes the SCFn fix for multi input Java functions
> Update to latest versions

- README.md
> Remove Helm instructions from README

- Makefile
- source/pulsar/templates.yaml
Create a single node pulsar install for internal use only.
> Publish internal-only-pulsar

- source/kpack/templates.yaml
- source/riff-builders/templates.yaml
and builder built with pack v0.8.0
> Update kpack to v0.0.6

- .github/workflows/acceptance.sh
- .github/workflows/ci.yaml
commands now conform to rfc 0003
> Upgrade riff dev-utils via FATS

- .github/workflows/acceptance.sh
- .github/workflows/ci.yaml
Cleanup how messages are consumed from a stream
> Consume latest dev-utils

- .github/workflows/acceptance.sh
- .github/workflows/ci.yaml
- .github/workflows/cleanup-riff.sh
- .github/workflows/install-riff.sh
Add the inmemory gateway for tests
Refs #136
> Decouple streaming tests from kafka

- .github/workflows/ci.yaml
- source/riff-build/templates.yaml
- source/riff-builders/templates.yaml
- source/riff-core-runtime/templates.yaml
- source/riff-knative-runtime/templates.yaml
- source/riff-streaming-runtime/templates.yaml
> Test Pulsar

- README.md
> Add missing k8s-tag-resolver prereq

- .github/workflows/cleanup-riff.sh
- .github/workflows/install-riff.sh
- Makefile
- README.md
- source/riff-bindings/templates.yaml
- source/riff-bindings/templates.yaml.tpl
- source/riff-build/templates.yaml
- source/riff-builders/templates.yaml
- source/riff-core-runtime/templates.yaml
- source/riff-knative-runtime/templates.yaml
- source/riff-streaming-runtime/templates.yaml
Building and installing riff-bindings as part of the release, but not yet using during acceptance tests.
> Add riff-bindings to release

- .github/workflows/ci.yaml
- source/riff-bindings/templates.yaml
- source/riff-build/templates.yaml
- source/riff-builders/templates.yaml
- source/riff-core-runtime/templates.yaml
- source/riff-knative-runtime/templates.yaml
- source/riff-streaming-runtime/templates.yaml
Updates the application builder image since the paketo team moved it and removed the previous builder
> Consume latest componets
