charts/projectriff-riff.yaml
Snapshot versions are replaced as there are new builds. This means that
we don't know exactly what is going into each chart. By pinning the
snapshot version to include a sha, we can lockdown the chart.
This also means that we'll need to update the chart whenever we need to
pick up a change. In time we can automate this process.
=> Pin free floating versions

Makefile, README.md, charts/riff/templates.yaml, charts/riff/templates.yaml.tpl, charts/update-template.sh
This adds template file that creates the templates.yaml file. (A bit
meta templating the config that defines how to chart's templates are
defined)
The `{chart}/templates.yaml.tpl` may contain bash expressions which are
resolved and inlined into the output file. The `make templates` target
will update existing chart templates. The output of this target should
be committed to the repo and pass CI before publishing a chart.
Running `make templates` is currently manual, but may be automated in
the future.
=> Maintainable pinned template versions

charts/riff/templates.yaml, ci/publish.sh, ci/stage.sh
The new format is `{version}-{date}-{sha}`, for example
`0.1.0-snapshot-201907190202-584c6a1d7b6e76f1`
=> Add timestamp and short gitsha to version slugs

charts/knative/Chart.yaml, charts/package.sh
- knative version is currently set to 0.7.1
Alternative to #27 
Fixes #25
=> Add app-version to knative and riff charts

Makefile, charts/package.sh, charts/riff-build/Chart.yaml, charts/riff-build/templates.yaml, charts/riff-build/templates.yaml.tpl, charts/riff-core-runtime/Chart.yaml, charts/riff-core-runtime/templates.yaml, charts/riff-core-runtime/templates.yaml.tpl, charts/riff-knative-runtime/Chart.yaml, charts/riff-knative-runtime/templates.yaml, charts/riff-knative-runtime/templates.yaml.tpl, charts/riff-streaming-runtime/Chart.yaml, charts/riff-streaming-runtime/templates.yaml, charts/riff-streaming-runtime/templates.yaml.tpl
The `0.5.0-snapshot` in the templates.yaml.tpl files should be replaced with `master` once projectriff/system#89 merges
=> Add a chart for each riff-system component

azure-pipelines.yml, charts/knative/Chart.yaml, charts/knative/templates.yaml, charts/knative/templates.yaml.tpl
This also will raise the minimum k8s version to 1.14 and expose the
serving.knative.dev/v1 api group.
=> Upgrade Knative Serving to 0.9

Makefile, charts/kpack/Chart.yaml, charts/kpack/templates.yaml, charts/kpack/templates.yaml.tpl, charts/riff-builders/Chart.yaml, charts/riff-builders/templates.yaml, charts/riff-builders/templates.yaml.tpl
Adding two new charts:
- kpack: wraps the kpack release distro
- riff-builders: the kpack equivalent of the knative buildtemplates
Disable the new charts by default until we are ready to fully replace
Knative Build with kpack.
=> Add charts for kpack and riff-builders

charts/riff-build/templates.yaml, charts/riff-builders/templates.yaml, charts/riff-core-runtime/templates.yaml, charts/riff-knative-runtime/templates.yaml, charts/riff-streaming-runtime/templates.yaml, charts/riff/templates.yaml, charts/riff/templates.yaml.tpl
Update all templates URLs. The riff-system URL is now pinned to the last
release since it is no longer published as a single artifact. The value
created by the template was no longer valid.
=> Pin URL for riff-system updated all others

Makefile, README.md, charts/riff/Chart.yaml, charts/riff/charts/riff-build, charts/riff/charts/riff-core-runtime, charts/riff/charts/riff-knative-runtime, charts/riff/charts/riff-streaming-runtime, charts/riff/requirements.yaml, charts/riff/values.yaml, ci/cleanup-riff.sh, ci/install-riff.sh
The riff chart encompasses all other charts (except for Istio). riff
Build and kpack are installed by default, but each runtime must be
explicitly enabled.
=> Add riff chart

charts/riff-build/templates.yaml, charts/riff-core-runtime/templates.yaml, charts/riff-knative-runtime/templates.yaml, charts/riff-streaming-runtime/templates.yaml
to prevent failures while creating functions.
fats is failing with Function.build.projectriff.io "fats-cluster-uppercase-java" is invalid
=> bumping system

Makefile, charts/cert-manager/Chart.yaml, charts/cert-manager/templates.yaml, charts/cert-manager/templates.yaml.tpl, ci/cleanup-riff.sh, ci/install-riff.sh
Cert Manger is used to issues tls certificats that are consumed by
kubebuilder MutationAdmissionWebhooks and ValidatingAdmissionWebhooks.
FATS will need to be updated to no longer kubectl apply the cert-manager
config in the no-resource-requests macro, but this needs to merge first.
Note: this is cert-manager 0.10, 0.11 introduces breaking changes and
is not backwards/forwards compatible.
Refs projectriff/system#102
=> Package cert-manager as a chart

README.md, charts/riff-build/templates.yaml, charts/riff-builders/templates.yaml, charts/riff-core-runtime/templates.yaml, charts/riff-knative-runtime/templates.yaml, charts/riff-streaming-runtime/templates.yaml, charts/riff/charts/cert-manager, charts/riff/requirements.yaml, charts/riff/values.yaml, ci/install-riff.sh
Cert-manager is now required. It will be installed with the riff chart
by default, or can be installed independently with the cert-manager
chart.
=> Update system and builders

overlays/crd-install.yml
- this should allow us to install, delete and install again without having to explicitly delete CRDs
=> Add hook-delete-policy to delete existing CRDs before creation

Makefile, charts/apply-template.sh, charts/istio/.gitignore, charts/istio/values.yaml.tpl, charts/package.sh, charts/riff-build/templates.yaml.tpl, charts/riff-builders/templates.yaml.tpl, charts/riff-core-runtime/templates.yaml.tpl, charts/riff-knative-runtime/templates.yaml.tpl, charts/riff-streaming-runtime/templates.yaml.tpl, charts/update-template.sh
We should avoid hard coding the Istio version in the Istio values.yaml
file. By templating the values we can resolve the Istio version and
consume new Istio releases by updating a single value.
This also updates the template format to evaluate expressions within
`{{ expr }}` instead of evaluating every line as a shell expression.
This makes escaping values that should not be matched much simpler as
only `{{ ... }}` will be evaluated.
Follow up to #78
=> Template Istio version

charts/keda/Chart.yaml, charts/keda/templates.yaml
There is no longer a single file, so we have many more URLs to download,
the namespace is also missing, so I created that resource and hosted on
our GCS bucket directly.
=> Update KEDA to v1.0.0

.github/workflows/install-riff-helm.sh, .github/workflows/install-riff-kapp.sh, charts/cert-manager/templates.yaml, charts/riff-build/templates.yaml, charts/riff-core-runtime/templates.yaml, charts/riff-knative-runtime/templates.yaml, charts/riff-streaming-runtime/templates.yaml
- includes updating to cert-manager v0.11.0
Fixes #94 
Depends on projectriff/system/pull/196
=> Update to latest templates and cert-manager v0.11.0

.github/workflows/ci.yaml, Makefile, charts/fetch-kafka.sh, charts/kafka/overlays-uncharted/inject-namespace.yaml, charts/kafka/overlays-uncharted/no-hooks.yaml, charts/kafka/uncharted.patch, charts/kafka/values.yaml, charts/package.sh, charts/unpackage.sh
We don't want to support a kafka install as part of riff, yet we need
kafka for our own tests. This chart/unchart is intended to fill that gap
but is not intended for end-users.
=> Publish kafka as an (un)chart

charts/keda/templates.yaml
The schema is breaking k8s 1.15+, These fields have been removed from
master, but is not yet in a release.
Refs projectriff/system#206
=> Update KEDA to remove schema validation for unused fields

.github/workflows/ci.yaml, .github/workflows/run-tests.sh, charts/riff-build/templates.yaml, charts/riff-core-runtime/templates.yaml, charts/riff-knative-runtime/templates.yaml, charts/riff-streaming-runtime/templates.yaml
This introduces two breaking changes:
- PodTemplateSpec has replaced PodSpec at `.spec.template`. The PodSpec
is now available at `.spec.template.spec`
- `.status.*Name` fields are now references named `.status.*Ref`. The
name is available at `.status.*Ref.name`. Where the name was
previously an empty string, the reference is nil.
=> Publish latest System

source/keda/overlays-release/crd-api-group-approval.yaml
Hack the KEDA CRDs to masquerade as approved to be in the k8s.io api
group. This should be remove once KEDA is no longer under the *.k8s.io
api group or is properly approved.
Fixes projectriff/riff#1377
=> Deploy KEDA to k8s 1.16 via kapp
